name: Vision Plus Scraper

on:
  workflow_dispatch: # Tombol manual di tab Actions
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install DrissionPage

    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

    - name: Run Scraper
      run: python jhk1k213.py

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: scraped-json-data
        path: debug_json/
